version: "3.7"

services:
    runner:
      container_name: github-runner
      image: tcardonne/github-runner:latest
      env_file:
        - runner.env
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock