name: build and run on lxhalle

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build
      run: |
        echo "Build…"
        make
        echo "Build done."

    - name: Run
      run: |
        echo "Run…"
        make run
        echo "Run done."
