name: C-Projekt-Beispiel

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build
      run: |
        echo "Build…"
        make build
        echo "Build done."

    - name: Run
      run: |
        echo "Run…"
        make run
        echo "Run done."
