name: C-Projekt-Beispiel

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build and Test
      run: |
        # Fügen Sie hier die Befehle hinzu, um Ihr C-Projekt zu kompilieren und zu testen
        # Zum Beispiel:
        # gcc -o my_project my_project.c
        # ./my_project --test
        echo "Hello World!!!"
